name: Daily Commit

on:
  schedule:
    # Runs daily at 10:05 UTC
    - cron: '5 10 * * *'
  workflow_dispatch:  # Manual trigger for testing

permissions:
  contents: write  # ✅ REQUIRED so GitHub Actions can push commits

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Commit by 25ds2000001@ds.study.iitm.ac.in
        run: |
          echo "Daily run at $(date)" >> daily_log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "25ds2000001@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Daily automated commit $(date)" || echo "No changes to commit"
          git push

